### PR TITLE
Add sdp files and update readme.

### PR DESCRIPTION
**Pull request by hendrik-vloet**

### CODE REVIEW

**Comment by themightyoarfish** [comment]
this repo isn't autocrane-specific. I'd put the sdp files into the autocrane repo instead

**Comment by hendrik-vloet** [comment]
@themightyoarfish fair point but they are of no usage without the streaming submodule, aren't they?

**Comment by themightyoarfish** [comment]
yeah, so? would be confusing having to go to some other repo to find files generated by autocrane

**Comment by hendrik-vloet** [comment]
Closing in favor of https://github.com/psiori/autocrane-core/pull/2257.

**Pull request closed without merging**
