### PR TITLE
SYSTEM before PRIVATE.

### PR DESCRIPTION
**Pull request by ahoereth**
https://cmake.org/cmake/help/latest/command/target_include_directories.html

core pr coming up

### CODE REVIEW

**Comment by ahoereth** [comment]
https://github.com/psiori/autocrane-core/pull/3244

**Comment by themightyoarfish** [comment]
any idea why that makes a difference? hard to believe

**Comment by ahoereth** [comment]
Besides breaking some paths, it impacts the order of the -I argument it?

```
[ 11%] Building CXX object CMakeFiles/encode_video_fromdir.dir/avtransmitter.cpp.o
/Library/Developer/CommandLineTools/usr/bin/c++ -DBOOST_THREAD_DYN_LINK -DBOOST_THREAD_NO_LIB -DZMQ_BUILD_DRAFT_API -I/Users/ahoereth/repos/autocrane-core/third_party/libffmpeg-zmq-streaming -I/Users/ahoereth/repos/autocrane-core/third_party/libffmpeg-zmq-streaming/SYSTEM -I/opt/homebrew/include -isystem /Users/ahoereth/repos/autocrane-core2/deps/include/opencv4 -isystem /Users/ahoereth/repos/autocrane-core2/deps/include -O2 -g -DNDEBUG -std=gnu++14 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk -MD -MT CMakeFiles/encode_video_fromdir.dir/avtransmitter.cpp.o -MF CMakeFiles/encode_video_fromdir.dir/avtransmitter.cpp.o.d -o CMakeFiles/encode_video_fromdir.dir/avtransmitter.cpp.o -c /Users/ahoereth/repos/autocrane-core/third_party/libffmpeg-zmq-streaming/avtransmitter.cpp
/Users/ahoereth/repos/autocrane-core/third_party/libffmpeg-zmq-streaming/avtransmitter.cpp:20:19: error: cannot initialize a variable of type 'AVOutputFormat *' with an rvalue of type 'const AVOutputFormat *'
  AVOutputFormat* format = av_guess_format("rtp", nullptr, nullptr);
                  ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/ahoereth/repos/autocrane-core/third_party/libffmpeg-zmq-streaming/avtransmitter.cpp:35:21: error: assigning to 'AVCodec *' from 'const AVCodec *' discards qualifiers
  this->out_codec = avcodec_find_encoder(AV_CODEC_ID_VP9);
```

vs 

```
[ 11%] Building CXX object CMakeFiles/encode_video_fromdir.dir/avtransmitter.cpp.o
/Library/Developer/CommandLineTools/usr/bin/c++ -DBOOST_THREAD_DYN_LINK -DBOOST_THREAD_NO_LIB -DZMQ_BUILD_DRAFT_API -I/Users/ahoereth/repos/autocrane-core/third_party/libffmpeg-zmq-streaming -isystem /Users/ahoereth/repos/autocrane-core2/deps/include/opencv4 -isystem /Users/ahoereth/repos/autocrane-core2/deps/include -isystem /opt/homebrew/include -O2 -g -DNDEBUG -std=gnu++14 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk -MD -MT CMakeFiles/encode_video_fromdir.dir/avtransmitter.cpp.o -MF CMakeFiles/encode_video_fromdir.dir/avtransmitter.cpp.o.d -o CMakeFiles/encode_video_fromdir.dir/avtransmitter.cpp.o -c /Users/ahoereth/repos/autocrane-core/third_party/libffmpeg-zmq-streaming/avtransmitter.cpp
```

**Comment by themightyoarfish** [comment]
maybe the system got ignored until now and thus this accidentally changes include order in this project and core

**Review by themightyoarfish — APPROVED** [review]

**Pull request merged**
